site_name: kiwoom-restful
site_url: https://github.com/breadum/kiwoom-restful

theme:
  name: material

extra:
  version: 
    provider: mike

nav:
  - Home: index.md
  - API: api.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
            show_if_no_docstring: true
            separate_signatrue: true
