site_name: kiwoom-restful
site_url: https://breadum.github.io/kiwoom-restful/
use_directory_urls: true

theme:
  name: material

extra:
  version: 
    provider: mike
    default: latest

extra_css:
  - css/extra.css

nav:
  - Home: index.md
  - API: api.md

plugins:
  - search
  - mike
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            members: __all__
            members_order: source
            show_source: true
            show_submodules: true
            separate_signature: true
            docstring_style: google
            show_if_no_docstring: true
            filters:
              - "!^__all__$"  # __all__ 숨김
              - "!^_"  # _ private 숨김
