site_name: kiwoom-restful
site_url: https://breadum.github.io/kiwoom-restful/
use_directory_urls: true

theme:
  name: material
  # palette:
  #   - scheme: default
  #     primary: indigo
  #     accent: indigo
  #   - scheme: slate
  #     primary: teal
  #     accent: teal
  # features:
  #   - navigation.tabs
  #   - navigation.top
  #   - search.highlight
  #   - search.suggest
  # palette:
  #   - scheme: default
  #     primary: blue
  #     accent: orange
  #   - scheme: slate
  #     primary: deep purple
  #     accent: pink

extra:
  version: 
    provider: mike
    default: latest

nav:
  - Home: index.md
  - API: api.md

plugins:
  - search
  - mike
  - mkdocstrings:
      handlers:
        python:
          options:
            members: __all__
            show_source: false
            separate_signature: true
            docstring_style: google
            show_root_heading: true
            show_if_no_docstring: false
            members_order: source
          
            filters:
              - "!^__all__$"  # __all__ 숨김
              - "!^__.*__$"   # dunder 변수 숨김
              - "!^_"         # private 멤버 숨김
