# This is a basic workflow to help you get started with Actions

name: Docs # MkDocs -> Github Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  release:
    types: [ published ]  # GitHub UI에서 Release를 Publish할 때만 동작
  workflow_dispatch:  # 수동 실행 허용

permissions:
  contents: read  # gh-pages에 커밋 푸시 필요

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install docs toolchain
        run: pip install mkdocs mkdocs-material mkdocstrings[python] mike

      - name: Configure git identity for gh-pages commits
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Compute version from release tag
        id: v
        run: |
          TAG="${{ github.event.release.tag_name }}"
          VER="${TAG#v}"
          echo "VER=$VER" >> $GITHUB_OUTPUT

      - name: Deploy docs with mike
        run: |
          mike deploy --push --update-aliases "{{ steps.v.outputs.VER }}" latest
          mike set-default --push latest
        
