# This is a basic workflow to help you get started with Actions

name: Docs # MkDocs -> Github Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  release:
    types: [ published ]  # GitHub UI에서 Release를 Publish할 때만 동작
  workflow_dispatch:  # 수동 실행 허용
    inputs:
      tag:
        description: "Tag v{version}. ex) v1.2.3"
        required: true

permissions:
  contents: write  # gh-pages에 커밋 푸시 필요

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install docs toolchain
        run: pip install mkdocs mkdocs-material mkdocstrings[python] mike
      
      - name: Install project
        run: pip install -e .

      - name: Configure git identity for gh-pages commits
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Sync gh-pages reference
        run: |
          git fetch origin gh-pages:gh-pages || true

      - name: Resolve version
        id: v
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            TAG="${{ github.event.release.tag_name }}"
          fi
          VER="${TAG#v}"
          echo "VER=$VER" >> $GITHUB_OUTPUT

      - name: Deploy docs with mike
        run: |
          mike deploy --push --update-aliases "${{ steps.v.outputs.VER }}" latest
          mike set-default --push latest
        
